services:
  - type: web
    name: owlsight-ai
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./out
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
      - path: /_next/static/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
